#!/bin/bash

function _iswin() {
  [ "${OS}" = "Windows_NT" ]
}

# temporary hack, to use scoop python39 by default with Windows
_iswin && alias python3=python39

################################################################################
# USUAL STUFF
################################################################################
alias l='ls --color -F --group-directories-first'
alias ll='ls -alF --color --group-directories-first'
alias lt='ls -altF --color --group-directories-first'
alias la='ls -aF --color --group-directories-first'
alias grep='grep --color'
alias du='/usr/bin/du -hc --max-depth=1'
alias df='df -h'
alias shred='shred -u'
alias hd=hexdump
alias tree='tree -C' # colors on

alias aupdate='sudo apt update'
alias ainstall='sudo apt install'

alias pipupgrade='python -m pip install --upgrade pip'
alias pip='python -m pip'
alias pip3='python3 -m pip'

################################################################################
# ALTERNATIVES
################################################################################

alias cat=bat

################################################################################
# VIM / GVIM
################################################################################
# use tabs to open multiple files with vim
alias vim='nvim -p'
# use tabs to open multiple files with gvim
alias gvim='gvim -p'


################################################################################
# PERSONAL SHORTCUTS
################################################################################
# Short date
alias sdate='date +%d.%m.%y-%H.%M.%S'

alias tmux='tmux attach'

alias livelog='watch --color -n 2 git --no-pager lag --color=always -35'

alias pytest='pytest -v'

alias psytags='ctags -R --map-c=+.psy'


################################################################################
# FUNCTIONS
################################################################################
# alias for "cd" then "ls"
function c {
    if [[ -z $* ]];
    then
        cd && l;
    else
        cd "$*" && l ;
    fi
}

# Run a command and issue a notification when it completes. Requires notify-py
# and Python
function notify() {
  ( ${*} && notifypy --title "✅ Command successful" --message "${*}" \
                     --applicationName "Console notify" ) || \
  notifypy --title "❌ Command failed" --message "${*}" \
           --applicationName "Console notify"
}

function _warnmsg() {
  echo "\033[1;33m"${*}"\033[0m"
}
function _errormsg() {
  echo "\033[1;31m"${*}"\033[0m"
}


function _confupgrade() {
  for dir in ~/.vim ~/.config/config;
  do
    echo "updating git repo in ${dir}"
    git -C ${dir} pff || _errormsg "Failed to fast-forward pull git repository!"

    if [ "$(git -C ${dir} status --porcelain)" ]; then
      _warnmsg "Warning: git repo ${dir} is not clean. Wanna push?"
    fi
  done

  # install vim updates
  echo "updating nvim plugins..."
  local _vimcmd='PlugUpgrade | PlugUpdate! | PlugClean! | quit! | quit!'
  nvim --headless -c "${_vimcmd}"

  # NodeJS global packages updates
  echo "updating nodejs packages"
  npm update -g

  # python packages
  echo "updating Python packages"
  pipx upgrade-all
}

function _pacmanupgrade() (
    set -e
    pacman="pacman"
    ${pacman} -Syu --noconfirm # update all
    orphans=$(${pacman} -Qtdq || exit 0)
    [ "${orphans}" ] && (${pacman} -Rns --noconfirm "${orphans}")
    ${pacman} -Sc --noconfirm # clear cache
)

function _scoopupgrade() (
  set -e
  scoop update
  scoop update "*"
  scoop cleanup "*"
  scoop cache rm -a
)

# upgrade windows tools
function wupgrade() (
  _iswin || {
    _warnmsg "You're not on Windows, dumbass!"; return
  }

  _pacmanupgrade

  _scoopupgrade

  _confupgrade

  touch "${HOME}/.config/.last_update"
)

function aupgrade() (
  set -e

  sudo apt update
  sudo apt upgrade --yes
  sudo apt autoremove --yes

  _confupgrade
)

function archupgrade() (
  # pamac upgrade (with AUR)
  pamac upgrade --aur --no-confirm

  # flatpak update
  flatpak update --assumeyes --noninteractive
  flatpak uninstall --assumeyes --unused

  _confupgrade

  touch "${HOME}/.config/.last_update"
)
