#!/bin/bash

################################################################################
# USUAL STUFF
################################################################################
alias l='ls --color -F --group-directories-first'
alias ll='ls -alF --color --group-directories-first'
alias lt='ls -altF --color --group-directories-first'
alias la='ls -aF --color --group-directories-first'
alias grep='grep --color'
alias du='du -hc --max-depth=1'
alias df='df -h'
alias shred='shred -u'

alias aupdate='sudo apt update'
alias aupgrade='sudo apt update && sudo apt upgrade && sudo apt autoremove'
alias ainstall='sudo apt install'

alias pipupgrade='python -m pip install --upgrade pip'

################################################################################
# VIM / GVIM
################################################################################
# use tabs to open multiple files with vim
alias vim='nvim -p'
# use tabs to open multiple files with gvim
alias gvim='gvim -p'


################################################################################
# PERSONAL SHORTCUTS
################################################################################
# Short date
alias sdate='date +%d.%m.%y-%H.%M.%S'

alias tmux='tmux attach'

alias tree='tree -I CVS --dirsfirst'

alias livelog='watch --color -n 2 git --no-pager lag --color=always -35'

alias pytest='pytest -v'



################################################################################
# FUNCTIONS
################################################################################

# upgrade windows tools
function wupgrade () (
  set -ex
  pacman -Syu
  scoop update "*"
  for dir in ~/vimfiles ~/.config/config;
  do
    echo "updating git repo in ${dir}"
    (cd ${dir} && git pff)
  done
)

# alias for "cd" then "ls"
function c {
    if [[ -z $* ]];
    then
        cd && l;
    else
        cd "$*" && l ;
    fi
}

# alias for merging SVN files using gvim
function pushtopath {
    export PATH=${1}:${PATH}
    echo Added ${1}
}

function md5tree {
    (
        [ ! -z $1 ] && [ -d $1 ] && cd $1 && \
            ( find . -type f | xargs md5sum ) ;
    )
}

function mktags {
    if [ "$1" == "" ];
    then
       DIR=.
    else
       DIR=$1
    fi
    find $DIR -name \*.\[cSh\] | xargs ctags
}

function aupgrade {
  (
    set -e
    sudo apt update
    sudo apt upgrade
    sudo apt autoremove
  )

  (cd ~/.vim && git pff)
  (cd ~/.config/config && git pff)
}
