#!zsh

# Be sure to:
# - KRONOSAFE_INSTALL_DIR
# - T32_DIR

function checkVarDefined () {
  [ -v ${1} ] || {
    local RED='\033[0;31m'
    local NC='\033[0m' # No Color
    printf "${RED}WARNING: variable ${1} (${2}) must be defined\n"
    return 1
  }
}

function _iswin() {
  [ "${OS}" = "Windows_NT" ]
}

checkVarDefined T32_DIR "Path to Trace32 root directory"
checkVarDefined KRONOSAFE_INSTALL_DIR "Root installation directory of ASTERIOS products"

################################################################################

# root directory of this script
_here="$(dirname ${0})"

# Python virtual environment
{ _iswin && _venv_sh="${_here}/.venv/Scripts/activate"; } || \
  _venv_sh="${_here}/.venv/bin/activate"
source ${_venv_sh}

export KS_HAAS_TOKEN="ffb4068cfea67f85eff848141f5f5317dccb6c824085fc13f36ee3c3c84be86e"
export JENKINS_USER="eohayon"
export JENKINS_TOKEN="11d3c39220afa89701e26e7bfa885e9980"

export HAAS_BOARDS="module-ccv2,module"
export PSYKO_PKG="psyko-9.2.1"

{ _iswin && export T32="${T32_DIR}/bin/windows64/t32mppc.exe"; } || \
  export T32="${T32_DIR}/bin/pc_linux64/t32mppc"

export VARIANT="power-mpc5777m-module-p"
export VARIANT_COV="power-mpc5777m-module-p-mcdc"
export RTK_PKG_REG="rtk-power-mpc5777m-module-5.2.1"
export RTK_PKG_DEV="rtk-power-mpc5777m-module-dev-5.2.1+fix.0"
export RTK_PKG="${RTK_PKG_REG}"
export COVERAGE_DIR="${KRONOSAFE_INSTALL_DIR}/${RTK_PKG_DEV}"
export BOOTLOADER="${KRONOSAFE_INSTALL_DIR}/${RTK_PKG_DEV}/${VARIANT}/bin/boot_ccv2/BOOT.elf"

alias mktags='ctags -R --languages=python,c,c++ _pylib component_tests/conftest.py rtk-mpc5777m/bundle rtk-mpc5777m/sources_bundle component_tests/lib'

# vim: set ft=sh:
