matches:
  - trigger: '""""'
    replace: "« $|$ »"
    word: true
  - trigger: " ? "
    replace: " ? "
  - trigger: " ! "
    replace: " ! "
  - trigger: " : "
    replace: " : "
  - trigger: " ; "
    replace: " ; "
  - trigger: "Ca"
    replace: "Ça"
    word: true
  - trigger: "oe "
    replace: "œ"
  - trigger: "OE "
    replace: "Œ"
  - trigger: "'E "
    replace: "É"
  - trigger: "`E"
    replace: "È"
  - trigger: "`A "
    replace: "À "
  - trigger: "... "
    replace: "… "
  - trigger: "--- "
    replace: "― "

